prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    enableRemoteWriteReceiver: true
    enableFeatures:
      - exemplar-storage

grafana:
  sidecar:
    datasources:
      exemplarTraceIdDestinations:
        datasourceUid: tempo
        traceIdLabelName: trace_id
  additionalDataSources:
    - name: "Loki"
      uid: "loki"
      type: "loki"
      url: "http://loki.monitoring:3100"
      jsonData:
        derivedFields:
          - name: TraceID
            matcherRegex: '"trace_id":"(\w+)"'
            datasourceUid: tempo
            url: '${__value.raw}'
    - name: "Tempo"
      uid: tempo
      type: tempo
      url: http://tempo.monitoring:3200
      jsonData:
        serviceMap:
          datasourceUid: prometheus
        tracesToLogsV2:
          datasourceUid: loki
          filterByTraceID: true

kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeControllerManager:
  enabled: false
kubeProxy:
  enabled: false
